---
title: "Entre Dev y Ops"
baseURL: "https://www.entredevyops.es/"

languageCode: "es-es"
defaultContentLanguage: "es"

SectionPagesMenu: "Main"
theme: "edyo"
paginate: 6
uglyurls: true
pygmentsCodeFences: true
pygmentsStyle: "vs"

enableEmoji: true

blackfriday:
  hrefTargetBlank: true

removePathAccents: false
preserveTaxonomyNames: false
taxonomies:
  tags: "tags"

outputFormats:
  RSS:
    mediatype: "application/rss"
    baseName: "rss"

security:
  exec:
    allow:
      - ^rst2html$

params:
  mainSections: ["posts", "podcasts"]

  Description: "El podcast en el que hablamos sobre desarrollo de aplicaciones, operaciones de sistemas informáticos y todo lo relacionado con la filosofía DevOps"
  Subtitle: "El podcast en el que hablamos sobre desarrollo de aplicaciones, operaciones de sistemas informáticos y todo lo relacionado con la filosofía DevOps"

  cover: "/images/cover.jpg"
  logo: "/images/edyo-logo.png"
  icon: "/images/edyo-icon.png"

  license: "<a target=\"_blank\" href=\"http://creativecommons.org/licenses/by-nc-sa/3.0/deed.es_ES\"><i class=\"fab fa-creative-commons\"></i> BY-NC-SA 3.0</a>"

  cookiesNoticePage: "politica-cookies.html"
  cookiesNoticeMessage: "Esta web utiliza cookies de terceros para mejorar la experiencia de la web y recopilar datos de uso. Si continúas navegando, consideramos que aceptas su uso."

  showToc: false

  googleAnalyticsUserID: "UA-25613214-1"

  disqus: "edyo"
  twitter: "entredevyops"
  LinkedIn: "EntreDevYOps"
  github: "edyo"
  telegram: "entredevyops"

  podcast:
    audioBaseUrl: "https://podcast.edyo.es/podcast/"

menu:
  main:
    - Name: "Episodios podcast"
      URL: "/podcasts.html"
      Identifier: "podcasts"
      Weight: 10
    - Name: "Artículos"
      URL: "/posts.html"
      Identifier: "posts"
      Weight: 20
    - Name: "Suscríbete"
      URL: "/suscribete.html"
      Identifier: "subscription"
      Weight: 30
    - Name: "Ayúdanos"
      URL: "/ayudanos.html"
      Identifier: "help-us"
      Weight: 40
    - Name: "Equipo"
      URL: "/equipo.html"
      Identifier: "team"
      Weight: 50
    - Name: "Código de conducta"
      URL: "/codigo-conducta.html"
      Identifier: "coc"
      Weight: 60

  frontpage:
    - Name: "Suscríbete"
      URL: "/suscribete.html"
      Pre: <i class="fas fa-rss"></i>
      Identifier: "subscription"
      Weight: 10
    - Name: "Ayúdanos"
      URL: "/ayudanos.html"
      Pre: <i class="fas fa-donate"></i>
      Identifier: "help-us"
      Weight: 20
